/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary:         'var(--color-primary)',
        'primary-mid':   'var(--color-primary-mid)',
        'primary-lt':    'var(--color-primary-lt)',
        'primary-soft':  'var(--color-primary-soft)',
        'primary-pale':  'var(--color-primary-pale)',
        accent:          'var(--color-accent)',
        'accent-lt':     'var(--color-accent-lt)',
        'accent-pale':   'var(--color-accent-pale)',
        surface:         'var(--color-surface)',
        'surface-2':     'var(--color-surface-2)',
        'bg-alt':        'var(--color-bg-alt)',
        text:            'var(--color-text)',
        'text-muted':    'var(--color-text-muted)',
        'text-faint':    'var(--color-text-faint)',
        border:          'var(--color-border)',
        success:         'var(--color-success)',
        error:           'var(--color-error)',
        warning:         'var(--color-warning)',
      },
      boxShadow: {
        xs:    'var(--shadow-xs)',
        sm:    'var(--shadow-sm)',
        md:    'var(--shadow-md)',
        lg:    'var(--shadow-lg)',
        xl:    'var(--shadow-xl)',
        glow:  'var(--shadow-glow)',
        card:  'var(--shadow-card)',
        'card-hover': 'var(--shadow-card-hover)',
      },
      borderRadius: {
        xs:   'var(--radius-xs)',
        sm:   'var(--radius-sm)',
        md:   'var(--radius-md)',
        lg:   'var(--radius-lg)',
        xl:   'var(--radius-xl)',
        '2xl':'var(--radius-2xl)',
        full: 'var(--radius-full)',
      },
      fontFamily: {
        display: ['Lora', 'Playfair Display', 'Georgia', 'serif'],
        body:    ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      },
      animation: {
        float:         'float 6s ease-in-out infinite',
        'float-slow':  'float-slow 8s ease-in-out infinite',
        shimmer:       'shimmer 2.5s linear infinite',
        'pulse-ring':  'pulse-ring 1.5s ease-out infinite',
        'pulse-soft':  'pulse-soft 2s ease-in-out infinite',
        'hair-flow':   'hair-flow 2s linear infinite',
        'gradient-shift': 'gradient-shift 8s ease infinite',
        'slide-up':    'slide-up 0.5s ease forwards',
        'fade-in':     'fade-in 0.4s ease forwards',
        'scale-in':    'scale-in 0.3s ease forwards',
        'leaf-sway':   'leaf-sway 4s ease-in-out infinite',
        'spin-slow':   'spin-slow 12s linear infinite',
      },
    },
  },
  plugins: [],
};
